/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpeakRouteImport } from './routes/_authenticated/speak'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVocabLangRouteImport } from './routes/_authenticated/vocab.$lang'
import { Route as AuthenticatedVideosLangRouteImport } from './routes/_authenticated/videos.$lang'
import { Route as AuthenticatedVideoIdRouteImport } from './routes/_authenticated/video.$id'
import { Route as AuthenticatedPlacementLangRouteImport } from './routes/_authenticated/placement.$lang'
import { Route as AuthenticatedOnboardingTargetRouteImport } from './routes/_authenticated/onboarding.target'
import { Route as AuthenticatedOnboardingPurposeRouteImport } from './routes/_authenticated/onboarding.purpose'
import { Route as AuthenticatedOnboardingLevelRouteImport } from './routes/_authenticated/onboarding.level'
import { Route as AuthenticatedOnboardingCommitmentRouteImport } from './routes/_authenticated/onboarding.commitment'
import { Route as AuthenticatedLessonIdRouteImport } from './routes/_authenticated/lesson.$id'
import { Route as AuthenticatedLearnLangRouteImport } from './routes/_authenticated/learn.$lang'
import { Route as AuthenticatedCourseIdRouteImport } from './routes/_authenticated/course.$id'
import { Route as AuthenticatedBooksLangRouteImport } from './routes/_authenticated/books.$lang'
import { Route as AuthenticatedBookIdRouteImport } from './routes/_authenticated/book.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpeakRoute = AuthenticatedSpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabLangRoute = AuthenticatedVocabLangRouteImport.update({
  id: '/vocab/$lang',
  path: '/vocab/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosLangRoute = AuthenticatedVideosLangRouteImport.update({
  id: '/videos/$lang',
  path: '/videos/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoIdRoute = AuthenticatedVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementLangRoute =
  AuthenticatedPlacementLangRouteImport.update({
    id: '/placement/$lang',
    path: '/placement/$lang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingTargetRoute =
  AuthenticatedOnboardingTargetRouteImport.update({
    id: '/target',
    path: '/target',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingPurposeRoute =
  AuthenticatedOnboardingPurposeRouteImport.update({
    id: '/purpose',
    path: '/purpose',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingLevelRoute =
  AuthenticatedOnboardingLevelRouteImport.update({
    id: '/level',
    path: '/level',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingCommitmentRoute =
  AuthenticatedOnboardingCommitmentRouteImport.update({
    id: '/commitment',
    path: '/commitment',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedLessonIdRoute = AuthenticatedLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnLangRoute = AuthenticatedLearnLangRouteImport.update({
  id: '/learn/$lang',
  path: '/learn/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseIdRoute = AuthenticatedCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksLangRoute = AuthenticatedBooksLangRouteImport.update({
  id: '/books/$lang',
  path: '/books/$lang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookIdRoute = AuthenticatedBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/speak': typeof AuthenticatedSpeakRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/books/$lang': typeof AuthenticatedBooksLangRoute
  '/course/$id': typeof AuthenticatedCourseIdRoute
  '/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/onboarding/commitment': typeof AuthenticatedOnboardingCommitmentRoute
  '/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/onboarding/purpose': typeof AuthenticatedOnboardingPurposeRoute
  '/onboarding/target': typeof AuthenticatedOnboardingTargetRoute
  '/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/video/$id': typeof AuthenticatedVideoIdRoute
  '/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/speak': typeof AuthenticatedSpeakRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/books/$lang': typeof AuthenticatedBooksLangRoute
  '/course/$id': typeof AuthenticatedCourseIdRoute
  '/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/onboarding/commitment': typeof AuthenticatedOnboardingCommitmentRoute
  '/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/onboarding/purpose': typeof AuthenticatedOnboardingPurposeRoute
  '/onboarding/target': typeof AuthenticatedOnboardingTargetRoute
  '/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/video/$id': typeof AuthenticatedVideoIdRoute
  '/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/speak': typeof AuthenticatedSpeakRoute
  '/_authenticated/book/$id': typeof AuthenticatedBookIdRoute
  '/_authenticated/books/$lang': typeof AuthenticatedBooksLangRoute
  '/_authenticated/course/$id': typeof AuthenticatedCourseIdRoute
  '/_authenticated/learn/$lang': typeof AuthenticatedLearnLangRoute
  '/_authenticated/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/_authenticated/onboarding/commitment': typeof AuthenticatedOnboardingCommitmentRoute
  '/_authenticated/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/_authenticated/onboarding/purpose': typeof AuthenticatedOnboardingPurposeRoute
  '/_authenticated/onboarding/target': typeof AuthenticatedOnboardingTargetRoute
  '/_authenticated/placement/$lang': typeof AuthenticatedPlacementLangRoute
  '/_authenticated/video/$id': typeof AuthenticatedVideoIdRoute
  '/_authenticated/videos/$lang': typeof AuthenticatedVideosLangRoute
  '/_authenticated/vocab/$lang': typeof AuthenticatedVocabLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/speak'
    | '/book/$id'
    | '/books/$lang'
    | '/course/$id'
    | '/learn/$lang'
    | '/lesson/$id'
    | '/onboarding/commitment'
    | '/onboarding/level'
    | '/onboarding/purpose'
    | '/onboarding/target'
    | '/placement/$lang'
    | '/video/$id'
    | '/videos/$lang'
    | '/vocab/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/speak'
    | '/book/$id'
    | '/books/$lang'
    | '/course/$id'
    | '/learn/$lang'
    | '/lesson/$id'
    | '/onboarding/commitment'
    | '/onboarding/level'
    | '/onboarding/purpose'
    | '/onboarding/target'
    | '/placement/$lang'
    | '/video/$id'
    | '/videos/$lang'
    | '/vocab/$lang'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/speak'
    | '/_authenticated/book/$id'
    | '/_authenticated/books/$lang'
    | '/_authenticated/course/$id'
    | '/_authenticated/learn/$lang'
    | '/_authenticated/lesson/$id'
    | '/_authenticated/onboarding/commitment'
    | '/_authenticated/onboarding/level'
    | '/_authenticated/onboarding/purpose'
    | '/_authenticated/onboarding/target'
    | '/_authenticated/placement/$lang'
    | '/_authenticated/video/$id'
    | '/_authenticated/videos/$lang'
    | '/_authenticated/vocab/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/speak': {
      id: '/_authenticated/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof AuthenticatedSpeakRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab/$lang': {
      id: '/_authenticated/vocab/$lang'
      path: '/vocab/$lang'
      fullPath: '/vocab/$lang'
      preLoaderRoute: typeof AuthenticatedVocabLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos/$lang': {
      id: '/_authenticated/videos/$lang'
      path: '/videos/$lang'
      fullPath: '/videos/$lang'
      preLoaderRoute: typeof AuthenticatedVideosLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video/$id': {
      id: '/_authenticated/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof AuthenticatedVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement/$lang': {
      id: '/_authenticated/placement/$lang'
      path: '/placement/$lang'
      fullPath: '/placement/$lang'
      preLoaderRoute: typeof AuthenticatedPlacementLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/target': {
      id: '/_authenticated/onboarding/target'
      path: '/target'
      fullPath: '/onboarding/target'
      preLoaderRoute: typeof AuthenticatedOnboardingTargetRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/purpose': {
      id: '/_authenticated/onboarding/purpose'
      path: '/purpose'
      fullPath: '/onboarding/purpose'
      preLoaderRoute: typeof AuthenticatedOnboardingPurposeRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/level': {
      id: '/_authenticated/onboarding/level'
      path: '/level'
      fullPath: '/onboarding/level'
      preLoaderRoute: typeof AuthenticatedOnboardingLevelRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/commitment': {
      id: '/_authenticated/onboarding/commitment'
      path: '/commitment'
      fullPath: '/onboarding/commitment'
      preLoaderRoute: typeof AuthenticatedOnboardingCommitmentRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/lesson/$id': {
      id: '/_authenticated/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AuthenticatedLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$lang': {
      id: '/_authenticated/learn/$lang'
      path: '/learn/$lang'
      fullPath: '/learn/$lang'
      preLoaderRoute: typeof AuthenticatedLearnLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course/$id': {
      id: '/_authenticated/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof AuthenticatedCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$lang': {
      id: '/_authenticated/books/$lang'
      path: '/books/$lang'
      fullPath: '/books/$lang'
      preLoaderRoute: typeof AuthenticatedBooksLangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$id': {
      id: '/_authenticated/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthenticatedBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingCommitmentRoute: typeof AuthenticatedOnboardingCommitmentRoute
  AuthenticatedOnboardingLevelRoute: typeof AuthenticatedOnboardingLevelRoute
  AuthenticatedOnboardingPurposeRoute: typeof AuthenticatedOnboardingPurposeRoute
  AuthenticatedOnboardingTargetRoute: typeof AuthenticatedOnboardingTargetRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingCommitmentRoute:
      AuthenticatedOnboardingCommitmentRoute,
    AuthenticatedOnboardingLevelRoute: AuthenticatedOnboardingLevelRoute,
    AuthenticatedOnboardingPurposeRoute: AuthenticatedOnboardingPurposeRoute,
    AuthenticatedOnboardingTargetRoute: AuthenticatedOnboardingTargetRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpeakRoute: typeof AuthenticatedSpeakRoute
  AuthenticatedBookIdRoute: typeof AuthenticatedBookIdRoute
  AuthenticatedBooksLangRoute: typeof AuthenticatedBooksLangRoute
  AuthenticatedCourseIdRoute: typeof AuthenticatedCourseIdRoute
  AuthenticatedLearnLangRoute: typeof AuthenticatedLearnLangRoute
  AuthenticatedLessonIdRoute: typeof AuthenticatedLessonIdRoute
  AuthenticatedPlacementLangRoute: typeof AuthenticatedPlacementLangRoute
  AuthenticatedVideoIdRoute: typeof AuthenticatedVideoIdRoute
  AuthenticatedVideosLangRoute: typeof AuthenticatedVideosLangRoute
  AuthenticatedVocabLangRoute: typeof AuthenticatedVocabLangRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpeakRoute: AuthenticatedSpeakRoute,
  AuthenticatedBookIdRoute: AuthenticatedBookIdRoute,
  AuthenticatedBooksLangRoute: AuthenticatedBooksLangRoute,
  AuthenticatedCourseIdRoute: AuthenticatedCourseIdRoute,
  AuthenticatedLearnLangRoute: AuthenticatedLearnLangRoute,
  AuthenticatedLessonIdRoute: AuthenticatedLessonIdRoute,
  AuthenticatedPlacementLangRoute: AuthenticatedPlacementLangRoute,
  AuthenticatedVideoIdRoute: AuthenticatedVideoIdRoute,
  AuthenticatedVideosLangRoute: AuthenticatedVideosLangRoute,
  AuthenticatedVocabLangRoute: AuthenticatedVocabLangRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
